Editors:
  connection: dbh
  tableName: editors
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    version:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
    creator_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: false
      autoincrement: false
    editor_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: false
      autoincrement: false
    datetime_created:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    datetime_edited:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    deleted:
      type: integer(1)
      fixed: false
      unsigned: true
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    status:
      type: integer(1)
      fixed: false
      unsigned: true
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    second_name:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    first_name:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    middle_name:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    email:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    login:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    password:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    password_salt:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    role:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    department:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    comment:
      type: string(1000)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Editor:
      class: Editors
      local: editor_id
      foreign: id
      type: one
    Creator:
      class: Editors
      local: creator_id
      foreign: id
      type: one
    History:
      local: id
      foreign: user_id
      type: many
Files:
  connection: dbh
  tableName: files
  columns:
    id:
      type: integer(4)
      fixed: 0
      unsigned: true
      primary: true
      autoincrement: true
    creator_id:
      type: integer(4)
      unsigned: true
      notnull: false
    created_at:
      type: timestamp(25)
      notnull: false
    model_name:
      type: string(255)
      notnull: true
    item_id:
      type: integer(4)
      unsigned: true
      notnull: true
    type:
      type: integer(1)
      unsigned: true
      default: '0'
      notnull: true
    title:
      type: string(255)
      notnull: true
    title_original:
      type: string()
      notnull: true
    size:
      type: integer(4)
      unsigned: true
      notnull: false
    hash:
      type: string(45)
      notnull: false
    ext:
      type: string(4)
      notnull: true
    path:
      type: string(512)
      notnull: true
  relations:
    Creator:
      class: Editors
      local: creator_id
      foreign: id
      type: one
History:
  connection: dbh
  tableName: history
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    user_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: false
      autoincrement: false
    datetime_action:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    table_name:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    content_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: false
      autoincrement: false
    column_name:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    content_version:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: false
      autoincrement: false
    content_old:
      type: string(10000)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    content_new:
      type: string(10000)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    action_type:
      type: integer(1)
      fixed: false
      unsigned: true
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Editors:
      local: user_id
      foreign: id
      type: one
