<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('files', 'files_creator_id_editors_id', array(
             'name' => 'files_creator_id_editors_id',
             'local' => 'creator_id',
             'foreign' => 'id',
             'foreignTable' => 'editors',
             ));
        $this->addIndex('files', 'files_creator_id', array(
             'fields' => 
             array(
              0 => 'creator_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('files', 'files_creator_id_editors_id');
        $this->removeIndex('files', 'files_creator_id', array(
             'fields' => 
             array(
              0 => 'creator_id',
             ),
             ));
    }
}