<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('files', array(
             'id' => 
             array(
              'type' => 'integer',
              'fixed' => '0',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'creator_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'notnull' => '',
              'length' => '4',
             ),
             'created_at' => 
             array(
              'type' => 'timestamp',
              'notnull' => '',
              'length' => '25',
             ),
             'model_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'item_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'notnull' => '1',
              'length' => '4',
             ),
             'type' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'default' => '0',
              'notnull' => '1',
              'length' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'title_original' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             'size' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'notnull' => '',
              'length' => '4',
             ),
             'hash' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '45',
             ),
             'ext' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '4',
             ),
             'path' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '512',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('files');
    }
}