<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('editors', 'editors_editor_id_editors_id', array(
             'name' => 'editors_editor_id_editors_id',
             'local' => 'editor_id',
             'foreign' => 'id',
             'foreignTable' => 'editors',
             ));
        $this->createForeignKey('editors', 'editors_creator_id_editors_id', array(
             'name' => 'editors_creator_id_editors_id',
             'local' => 'creator_id',
             'foreign' => 'id',
             'foreignTable' => 'editors',
             ));
        $this->addIndex('editors', 'editors_editor_id', array(
             'fields' => 
             array(
              0 => 'editor_id',
             ),
             ));
        $this->addIndex('editors', 'editors_creator_id', array(
             'fields' => 
             array(
              0 => 'creator_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('editors', 'editors_editor_id_editors_id');
        $this->dropForeignKey('editors', 'editors_creator_id_editors_id');
        $this->removeIndex('editors', 'editors_editor_id', array(
             'fields' => 
             array(
              0 => 'editor_id',
             ),
             ));
        $this->removeIndex('editors', 'editors_creator_id', array(
             'fields' => 
             array(
              0 => 'creator_id',
             ),
             ));
    }
}