<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('editors', 'id', 'integer', '4', array(
             'fixed' => '0',
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('editors', 'version', 'integer', '4', array(
             'fixed' => '0',
             'unsigned' => '1',
             'primary' => '',
             'default' => '1',
             'notnull' => '1',
             'autoincrement' => '',
             ));
        $this->changeColumn('editors', 'creator_id', 'integer', '4', array(
             'fixed' => '0',
             'unsigned' => '1',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('editors', 'editor_id', 'integer', '4', array(
             'fixed' => '0',
             'unsigned' => '1',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('editors', 'datetime_created', 'timestamp', '25', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('editors', 'datetime_edited', 'timestamp', '25', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('editors', 'deleted', 'integer', '1', array(
             'fixed' => '0',
             'unsigned' => '1',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             ));
        $this->changeColumn('editors', 'status', 'integer', '1', array(
             'fixed' => '0',
             'unsigned' => '1',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             ));
        $this->changeColumn('editors', 'second_name', 'string', '100', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('editors', 'first_name', 'string', '100', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('editors', 'middle_name', 'string', '100', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('editors', 'email', 'string', '100', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('editors', 'login', 'string', '32', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('editors', 'password', 'string', '255', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('editors', 'password_salt', 'string', '32', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('editors', 'role', 'string', '32', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('editors', 'department', 'string', '100', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('editors', 'comment', 'string', '1000', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('history', 'id', 'integer', '4', array(
             'fixed' => '0',
             'unsigned' => '1',
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('history', 'user_id', 'integer', '4', array(
             'fixed' => '0',
             'unsigned' => '1',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('history', 'datetime_action', 'timestamp', '25', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('history', 'table_name', 'string', '64', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '1',
             'autoincrement' => '',
             ));
        $this->changeColumn('history', 'content_id', 'integer', '4', array(
             'fixed' => '0',
             'unsigned' => '1',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('history', 'column_name', 'string', '64', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('history', 'content_version', 'integer', '4', array(
             'fixed' => '0',
             'unsigned' => '1',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('history', 'content_old', 'string', '10000', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('history', 'content_new', 'string', '10000', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->changeColumn('history', 'action_type', 'integer', '1', array(
             'fixed' => '0',
             'unsigned' => '1',
             'primary' => '',
             'notnull' => '1',
             'autoincrement' => '',
             ));
    }

    public function down()
    {

    }
}