<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('items', 'value');
        $this->addColumn('items', 'title', 'string', '', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->addColumn('items', 'value', 'string', '', array(
             'notnull' => '',
             ));
        $this->removeColumn('items', 'title');
    }
}