-- MySQL Script generated by MySQL Workbench
-- Пн 18 мар 2019 21:13:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `migration_version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `migration_version` (
  `version` INT(11) NOT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARSET = utf8;


-- -----------------------------------------------------
-- Table `editors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `editors` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Идентификатор',
  `second_name` VARCHAR(125) DEFAULT NULL COMMENT 'Фамилия',
  `first_name` VARCHAR(125) DEFAULT NULL COMMENT 'Имя',
  `middle_name` VARCHAR(125) DEFAULT NULL COMMENT 'Отчество',
  `email` VARCHAR(125) DEFAULT NULL COMMENT 'Эл. почта',
  `phone` VARCHAR(125) DEFAULT NULL COMMENT 'Телефон',
  `login` VARCHAR(31) DEFAULT NULL COMMENT 'Логин',
  `password` VARCHAR(255) DEFAULT NULL COMMENT 'Пароль',
  `password_salt` VARCHAR(31) DEFAULT NULL COMMENT 'Соль пароля',
  `request_password_change` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Требование смены пароля',
  `role` VARCHAR(31) DEFAULT NULL COMMENT 'Роль',
  `department` VARCHAR(125) DEFAULT NULL COMMENT 'Подразделение',
  `comment` TEXT COMMENT 'Комментарий',
  `version` INT(10) UNSIGNED NOT NULL DEFAULT '1' COMMENT 'Версия',
  `creator_id` INT(10) UNSIGNED DEFAULT NULL COMMENT 'Создал',
  `editor_id` INT(10) UNSIGNED DEFAULT NULL COMMENT 'Последним изменил',
  `datetime_created` DATETIME DEFAULT NULL COMMENT 'Дата и время создания',
  `datetime_edited` DATETIME DEFAULT NULL COMMENT 'Дата и время последнего изменения',
  `deleted` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Удалено',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Статус',
  PRIMARY KEY (`id`),
  KEY `editors_creator_id_idx` (`creator_id`),
  KEY `editors_editor_id_idx` (`editor_id`),
  CONSTRAINT `editors_creator_id_editors_id`
    FOREIGN KEY (`creator_id`)
    REFERENCES `editors` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `editors_editor_id_editors_id`
    FOREIGN KEY (`editor_id`)
    REFERENCES `editors` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARSET = utf8;

-- User for tests
-- tester / topsecurity+
INSERT INTO `editors` (second_name, first_name, email, login, password, password_salt, role, comment)
VALUES ('Tester', 'Actor', 'tester@localhost.com', 'tester', '655ed8d6dd71f130e9c9de02f70eab7a', '5ca4cb6f2d8f0', 'admin', 'topsecurity+');


-- -----------------------------------------------------
-- Table `history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `history` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED DEFAULT NULL,
  `datetime_action` DATETIME DEFAULT NULL,
  `table_name` VARCHAR(64) NOT NULL,
  `content_id` INT(10) UNSIGNED DEFAULT NULL,
  `column_name` VARCHAR(64) DEFAULT NULL,
  `content_version` INT(10) UNSIGNED DEFAULT NULL,
  `content_old` TEXT,
  `content_new` TEXT,
  `action_type` TINYINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  KEY `history_user_id_idx` (`user_id`),
  CONSTRAINT `history_user_id_editors_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `editors` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARSET = utf8;


-- -----------------------------------------------------
-- Table `files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `files` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Идентификатор',
  `model_name` VARCHAR(255) DEFAULT NULL COMMENT 'Модель записи, к которой привязан файл',
  `item_id` INT(10) UNSIGNED DEFAULT NULL COMMENT 'ID записи, к которой привязан файл',
  `type` TINYINT(3) UNSIGNED DEFAULT NULL COMMENT 'Тип связи с записью, к которой привязан файл (код в схеме)',
  `title` TEXT NOT NULL COMMENT 'Название файла',
  `title_original` TEXT NOT NULL COMMENT 'Название исходного файла',
  `size` INT(10) UNSIGNED DEFAULT NULL COMMENT 'Размер файла в байтах',
  `hash` VARCHAR(45) DEFAULT NULL COMMENT 'Хэш сумма от файла',
  `ext` VARCHAR(7) NOT NULL COMMENT 'Расширение файла',
  `path` TEXT NOT NULL COMMENT 'Путь до файла',
  `version` INT(10) UNSIGNED NOT NULL DEFAULT '1' COMMENT 'Версия',
  `creator_id` INT(10) UNSIGNED DEFAULT NULL COMMENT 'Создал',
  `editor_id` INT(10) UNSIGNED DEFAULT NULL COMMENT 'Последним изменил',
  `datetime_created` DATETIME DEFAULT NULL COMMENT 'Дата и время создания',
  `datetime_edited` DATETIME DEFAULT NULL COMMENT 'Дата и время последнего изменения',
  `deleted` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Удалено',
  PRIMARY KEY (`id`),
  KEY `files_creator_id_idx` (`creator_id`),
  KEY `files_editor_id_idx` (`editor_id`),
  CONSTRAINT `files_creator_id_editors_id`
    FOREIGN KEY (`creator_id`)
    REFERENCES `editors` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `files_editor_id_editors_id`
    FOREIGN KEY (`editor_id`)
    REFERENCES `editors` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARSET = utf8;


-- -----------------------------------------------------
-- Table `tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tasks` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Идентификатор',
  `created_at` DATETIME NOT NULL COMMENT 'Дата добавления',
  `scheduled_at` DATETIME DEFAULT NULL COMMENT 'Плановое время запуска',
  `done_at` DATETIME DEFAULT NULL COMMENT 'Окончание исполнения',
  `performer_code` VARCHAR(63) NOT NULL COMMENT 'Код исполнителя',
  `related_id` int(10) UNSIGNED DEFAULT NULL COMMENT 'Объект исполнения',
  `state` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Состояние',
  `errors` TEXT COMMENT 'Ошибки',
  `root_id` BIGINT(20) DEFAULT NULL,
  `lft` INT(11) DEFAULT NULL,
  `rgt` INT(11) DEFAULT NULL,
  `level` SMALLINT(6) DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARSET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
