-- MySQL Script generated by MySQL Workbench
-- Пн 18 мар 2019 21:13:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `migration_version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `migration_version` (
  `version` INT NOT NULL,
  PRIMARY KEY (`version`));


-- -----------------------------------------------------
-- Table `editors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `editors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Идентификатор',
  `version` INT UNSIGNED NOT NULL DEFAULT '1',
  `creator_id` INT UNSIGNED NULL,
  `editor_id` INT UNSIGNED NULL,
  `datetime_created` TIMESTAMP NULL,
  `datetime_edited` TIMESTAMP NULL,
  `deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `second_name` VARCHAR(125) NULL COMMENT 'Фамилия',
  `first_name` VARCHAR(125) NULL COMMENT 'Имя',
  `middle_name` VARCHAR(125) NULL COMMENT 'Отчество',
  `email` VARCHAR(125) NULL COMMENT 'Эл. почта',
  `phone` VARCHAR(125) NULL COMMENT 'Телефон',
  `login` VARCHAR(31) NULL COMMENT 'Логин',
  `password` VARCHAR(255) NULL COMMENT 'Пароль',
  `password_salt` VARCHAR(31) NULL COMMENT 'Соль пароля',
  `request_password_change` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Требование смены пароля',
  `role` VARCHAR(31) NULL COMMENT 'Роль',
  `department` VARCHAR(125) NULL COMMENT 'Подразделение',
  `comment` VARCHAR(1000) NULL COMMENT 'Комментарий',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- User for tests
-- tester / topsecurity+
INSERT INTO `editors` (second_name, first_name, email, login, password, password_salt, role, comment)
VALUES ('Tester', 'Actor', 'tester@localhost.com', 'tester', '655ed8d6dd71f130e9c9de02f70eab7a', '5ca4cb6f2d8f0', 'admin', 'topsecurity+');


-- -----------------------------------------------------
-- Table `history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `history` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NULL,
  `datetime_action` TIMESTAMP NULL,
  `table_name` VARCHAR(64) NOT NULL,
  `content_id` INT UNSIGNED NULL,
  `column_name` VARCHAR(64) NULL,
  `content_version` INT UNSIGNED NULL,
  `content_old` VARCHAR(10000) NULL,
  `content_new` VARCHAR(10000) NULL,
  `action_type` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_history_editors_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `editors` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;

CREATE INDEX `FK_history_editors_1_idx` ON `history` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `files` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Идентификатор',
  `version` INT UNSIGNED NOT NULL DEFAULT '1',
  `creator_id` INT UNSIGNED NULL,
  `editor_id` INT UNSIGNED NULL,
  `datetime_created` TIMESTAMP NULL,
  `datetime_edited` TIMESTAMP NULL,
  `deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `model_name` varchar(255) NOT NULL COMMENT 'Модель записи, к которой привязан файл',
  `item_id` int(10) UNSIGNED NOT NULL COMMENT 'ID записи, к которой привязан файл',
  `type` tinyint(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Тип связи с записью, к которой привязан файл (код в схеме)',
  `title` varchar(255) NOT NULL COMMENT 'Название исходного файла',
  `size` int(10) UNSIGNED DEFAULT NULL COMMENT 'Размер файла в байтах',
  `hash` varchar(45) DEFAULT NULL COMMENT 'Хэш сумма от файла',
  `ext` varchar(7) NOT NULL COMMENT 'Расширение файла',
  `path` varchar(511) NOT NULL COMMENT 'Путь до файла',
  PRIMARY KEY (`id`),
  KEY `FK_files_creator_id_idx` (`creator_id`),
  CONSTRAINT `FK_files_creator_id_editors_id`
    FOREIGN KEY (`creator_id`)
    REFERENCES `editors` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tasks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Идентификатор',
  `created_at` TIMESTAMP NOT NULL COMMENT 'Дата добавления',
  `scheduled_at` TIMESTAMP NULL COMMENT 'Плановое время запуска',
  `done_at` TIMESTAMP NULL COMMENT 'Окончание исполнения',
  `performer_code` VARCHAR(63) NOT NULL COMMENT 'Код исполнителя',
  `related_id` INT UNSIGNED NULL COMMENT 'Объект исполнения',
  `state` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Состояние',
  `errors` VARCHAR(1000) NULL COMMENT 'Ошибки',
  `lft` INT UNSIGNED NULL,
  `rgt` INT UNSIGNED NULL,
  `level` INT UNSIGNED NULL,
  `root_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
