<?php

/**
 * Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Items extends BaseItems implements ZFE_File_Manageable
{
    /**
     * Половая принадлежность записи.
     *
     * @var int
     */
    public static $sex = self::SEX_MALE;

    /**
     * Название записи в единственном числе.
     *
     * @var string
     */
    public static $nameSingular = 'Запись';

    /**
     * Название записи во множественном числе.
     *
     * @var string
     */
    public static $namePlural = 'Записи';

    /**
     * Писать историю.
     *
     * @var bool
     */
    public static $saveHistory = true;

    /**
     * Имена полей записи модели.
     *
     * Дополняет self::$_nameBaseFields.
     *
     * @var array
     */
    public static $nameFields = [];

    /**
     * Поле (выражение) названия записи.
     *
     * @var string
     */
    public static $titleField = 'x.title';

    /**
     * Сортировка записей по умолчанию.
     *
     * @var string
     */
    public static $defaultOrder = 'x.id DESC';

    /**
     * Ключ сортировки по умолчанию.
     *
     * @var string
     */
    public static $defaultOrderKey = 'id_desc';

    /**
     * Имя контроллера управляющего записями модели.
     *
     * @var string
     */
    public static $controller;

    /**
     * Записи могут быть объединены стандартным способом?
     *
     * @var bool
     */
    public static $mergeable = false;

    /**
     * @inheritDoc
     */
    public function getFileManager($accessControl, Editors $user = null): ZFE_File_Manager
    {
        $fm = new ZFE_File_Manager_Default($this, Zend_Registry::get('config')->files);
        if ($accessControl) $fm->initAccessControl(Zend_Registry::get('acl'), $user);
        return $fm;
    }
}