#!/usr/bin/php
<?php
/**
 * Doctrine CLI script
 */

require_once __DIR__ . '/../vendor/autoload.php';

// Define application environment
defined('APPLICATION_ENV')
|| define('APPLICATION_ENV', (getenv('APPLICATION_ENV') ? getenv('APPLICATION_ENV') : 'production'));
require_once __DIR__ . '/../constants.php';

// Create application, bootstrap, and run
$application = new Zend_Application(
    APPLICATION_ENV,
    APPLICATION_PATH . '/configs/application.ini'
);

$application->getBootstrap()
    ->bootstrap('config')
    ->bootstrap('loader')
    ->bootstrap('doctrine')
;

/**
 * Скрипт для актуализации описания моделей
 *
 * Скрипт берет $config->yaml_schema_path (schema.yml) как актуальное описание схемы и:
 * 1. генерирует файл миграции по разнице между описанием в схеме и описаниями в существующих моделях с помощью задачи generate-migrations-diff
 * 2. и обновляет описание моделей, приводя их в соответсвие с описанием в схеме, с помощью задачи generate-models-yaml
 */

$config = Zend_Registry::get('config')->doctrine;
if ($config->get('rethrow_exceptions') === null) {
    echo "Параметр rethrow_exceptions не указан в doctrine.ini, запуск без него чреват нарушением порядка действий!\n"; exit(0);
}

$cli = new Doctrine_Cli(Zend_Registry::get('config')->doctrine->toArray());

/**
 * Эти файлы храняться в library/doctrine1/lib/Doctrine/Parser/sfYaml
 * Они не поддерживают общий для Doctrine PSR-0 и не имеют пространства имен.
 * В Doctrine_Core::autoload есть специальный блок для обработки этих файлов, что намекает,
 * что эти файлы из какой-то сторонней библиотеки.
 * В любом случае, я не знаю, почему они не подгружаются автоматически, но они нужны для задачи  generate-migrations-diff
 */
Doctrine_Core::autoload('sfYaml');
Doctrine_Core::autoload('sfYamlDumper');
Doctrine_Core::autoload('sfYamlParser');

try {
    $cli->run([__FILE__, 'generate-migrations-diff']);
} catch (Doctrine_Task_Exception $e) {
    echo join('', [$e->getMessage(), "Описания моделей соответствует описанию схемы\n"]);
    exit(0);
}

$cli->run([__FILE__, 'generate-models-yaml']);