#!/usr/bin/php
<?php
/**
 * Doctrine CLI script
 */

require_once __DIR__ . '/../vendor/autoload.php';
require_once __DIR__ . '/../constants.php';

// Create application, bootstrap, and run
$application = new Zend_Application(
    APPLICATION_ENV,
    APPLICATION_PATH . '/configs/application.ini'
);

$application->getBootstrap()
    ->bootstrap('config')
    ->bootstrap('loader')
    ->bootstrap('doctrine')
;

$cli = new Doctrine_Cli(Zend_Registry::get('config')->doctrine->toArray());
$cli->run($_SERVER['argv']);
